services:
  server:
    build: .
    container_name: temasi-server-image
    environment:
      - DSN=postgresql://postgres:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - "db"
    restart: unless-stopped
    ports:
      - 80:3000
    networks: 
      - server_network
  db:
    image: 'postgres:latest'
    container_name: 'temasi-db-image'
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    expose:
      - 5432
    ports:
      - 5678:5432
    networks: 
      - server_network
networks:
  server_network: