export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

export const SET_LOADING = 'SET_LOADING';

export const SET_STATUS = 'SET_STATUS';
export const CLEAR_STATUS = 'CLEAR_STATUS';

export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const SET_UPLOAD_RESULT = 'SET_UPLOAD_RESULT';

export const SUBMIT_PERMOHONAN = 'SUBMIT_PERMOHONAN';
