export const ADD_ACCOUNT = 'ADD_ACCOUNT';
export const DELETE_ACCOUNT = 'DELETE_ACCOUNT';

export const SET_LOADING = 'SET_LOADING';

export const SET_STATUS = 'SET_STATUS';
export const CLEAR_STATUS = 'CLEAR_STATUS';

export const LOGIN_USER = 'LOGIN_USER';
export const REGISTER_USER = 'REGISTER_USER';

export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const SET_UPLOAD_RESULT = 'SET_UPLOAD_RESULT';

export const SUBMIT_PERMOHONAN = 'SUBMIT_PERMOHONAN';
export const SEARCH_PERMOHONAN = 'SEARCH_PERMOHONAN';
export const GET_LATEST_PERMOHONAN = 'GET_LATEST_PERMOHONAN';
export const GET_URGENT_PERMOHONAN = 'GET_URGENT_PERMOHONAN';
export const GET_SELF_PERMOHONAN = 'GET_SELF_PERMOHONAN';
export const GET_DONATUR_PERMOHONAN_DETAIL = 'GET_DONATUR_PERMOHONAN_DETAIL';
export const SET_SEARCH_PERMOHONAN_RESULT = 'SET_SEARCH_PERMOHONAN_RESULT';
export const SET_LATEST_PERMOHONAN = 'SET_LATEST_PERMOHONAN';
export const SET_URGENT_PERMOHONAN = 'SET_URGENT_PERMOHONAN';
export const SET_SELF_PERMOHONAN = 'SET_SELF_PERMOHONAN';
export const SET_DONATUR_PERMOHONAN_DETAIL = 'SET_DONATUR_PERMOHONAN_DETAIL';

export const GET_DONASI = 'GET_DONASI';
export const GET_DONASI_DETAL = 'GET_DONASI_DETAIL';
export const ACCEPT_DONASI = 'ACCEPT_DONASI';
export const CONFIRM_DONASI_RECEIVED = 'CONFIRM_DONASI_RECEIVED';
export const SET_DONASI = 'SET_DONASI';
export const SET_DONASI_DETAIL = 'SET_DONASI_DETAIL';
